# in config/database.yml
# this defines the database for the development environment (default environment)
development:
  # the type of database it will be
  adapter:
    postgresql
    # name of db to make
  database: cloudbnb-development
  host: localhost

  # same but for test env
test:
  adapter: postgresql
  database: cloudbnb-test
